#server:
#  port: 8063
#  context-path: /mall-app
#
#mybatis:
#  mapper-locations: classpath*:com/gs/mall/**/dao/config/*.xml
#  executor-type: simple
#
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.2.238:3306/gs_mall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    username: root
#    password: 123654
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    maxActive: 10
#    initialSize: 2
#    maxWait: 60000
#    minIdle: 1
#  http:
#    encoding:
#      charset: UTF-8
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#
#
#jedis:
#  address: 192.168.2.238
#  port: 6379
#  auth: d7f153db47f04b24
#  maxIdle: 300
#  maxActive: 600
#  maxWait: 1000
#  testOnBorrow: true
#
##thread pool config
#thread.pool:
#  corePoolSize: 5
#  maxPoolSize: 10
#  keepAliveSeconds: 300
#  #queueCapacity: 2147483647
#
##solr config
#solr.url: http://192.168.2.237:6081/solr/
#
#mall.pay.callback.url: http://192.168.2.238:8063/mall-app/app/order/callback/paymentCallback
#mall.close.callback.url: http://192.168.2.238:8063/mall-app/app/order/callback/closeCallback
#mall.refund.callback.url: http://192.168.2.238:8063/mall-app/manage/workOrder/callback/refundCallback
#
#
##mall freight limit
#mall.freight.limit: 15
#
##app entrance uri
#mall.app.entrance.uri: /app/banner/all
#
##time config
#mall.pay.timeout.minute: 60
#mall.deliver.timeout.day: 15
#mall.inventory.retry.time: 10
#
##oss config
#oss.test.env: 1
#oss.gs.mall.key: export/mall
#oss.test.file.path: /var/log/webapps/mall_oss
#oss.file.path: /var/log/webapps/mall_oss/single_file
#oss.access.id: DFTBZA4KpoWWGUdi
#oss.access.key: 5uBQ6gYt6PEa3hqRdHnkMJLrhFFdIk
##外网上传地址
#oss.endpoint: http://oss-cn-shanghai.aliyuncs.com
##内网上传地址
##oss.endpoint=http://oss-cn-shanghai-internal.aliyuncs.com
#oss.bucketname.temp: gsg-temp
#oss.ossurl.temp: http://temp.goodsogood.com/
#
#gs.mq:
#    providerSerAddrs: 192.168.2.237:4151
#    consumerSerAddrs: 192.168.2.237:4161
#    autoStart: true
#    charset: UTF-8
#    
#openapi:
#  openApiHost: http://192.168.2.237:18083
